<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/umfa-default.css'));
$this->headLink()->appendStylesheet($this->assetUrl('css/bootstrap-grid.min.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/collapse.js'));
$this->jsTranslate();
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?><head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        
        
	
	<!-- Theme Option css -->	
	
	<?php if ($this->themeSetting('header_layout') == 'second'): ?>
	    <link href="/themes/UMFA-default/asset/css/left-header.css" rel="stylesheet"/>
	<?php endif; ?>
	
	<?php if ($this->themeSetting('nav_absolute_top') == 'second'): ?>
	    <link href="/themes/UMFA-default/asset/css/absolute-topNav.css" rel="stylesheet"/>
	<?php endif; ?>
	
	<?php if ($this->themeSetting('item_meta_layout') == 'second'): ?>
	    <link href="/themes/UMFA-default/asset/css/item-meta-layout-condensed.css" rel="stylesheet"/>
	<?php endif; ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        
    <a id="skipnav" href="#content"><?php echo $this->translate('Skip to main content'); ?></a>
        <?php echo $userBar; ?>
        <header>
			
			<div class="site-title-container">
				
					<a href="<?php echo $site->url(); ?>" class="site-title">
						<h1>
					<?php if ($this->themeSetting('logo')): ?>
						<img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
					<?php else: ?>
						<?php echo $escape($siteTitle); ?>
					<?php endif; ?>
						</h1>
					</a>
				
				<button class="nav-search-btn" onclick="document.getElementById('search-container').classList.toggle('closed');"> </button>
			</div>
            <nav <?php if ($this->themeSetting('header_layout') == 'second'): ?>class="position-left"<?php endif; ?>>
            <?php
            echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1
            ]);
            ?>
            </nav>
			
			<div id="search-container" class="closed" >
				<div id="search">
                	<?php echo $this->partial('common/search-form'); ?>
				</div>
            </div>
        </header>
        <div id="content" role="main">
            <?php echo $this->content; ?>
        </div>
<div class="marriott-branding"><a href="https://utah.edu" class="ulogo"><img src="/themes/UMFA-default/images/ulogo.png" alt="University of Utah" /></a> A digital publication from the <a href="https://lib.utah.edu">J. Willard Marriott Library</a>  and the <a href="https://umfa.utah.edu/">Utah Museum of Fine Arts</a></div>
        <footer>
            <?php if ($footerContent = $this->themeSetting('footer')): ?>
            <?php echo $footerContent; ?>
            <?php else: ?>
                <?php echo $this->translate('Powered by Omeka S'); ?>
            <?php endif; ?>
			
        </footer>

<!-- Theme Color Changes -->
<style>

<?php if ($this->themeSetting('header_border_color')): ?>
	header { border-color: <?php echo $this->themeSetting('header_border_color'); ?>; }	
<?php endif; ?>
<?php if ($this->themeSetting('hide_breadcrumbs') == 'second'): ?>
	.breadcrumbs { display: block; }	
<?php endif; ?>			

</style>
    </body>
</html>
